## Lychee configuration for link checking (TOML)
# Use TOML so the lychee action's parser won't fail.

# Output format used by lychee (keeps logs readable in GitHub Actions)
# Valid options: Compact, Detailed, Json, Markdown, Raw
# Use Markdown for GitHub-friendly output.
format = "Markdown"

# Maximum seconds to wait for network requests
timeout = 20

# Explicit list of URLs to ignore (these remain in the page but won't fail CI)
# Add exact paths here; if you later want to exclude whole hosts, add their root URL
exclude = [
	"https://lp.constantcontactpages.com/sl/Cqimxm7/csdac",
	"https://www.instagram.com/corona_sda_church"
]

# Note: add additional URLs here if you find reliable false-positives
# (for example, marketing or third-party landing pages that block automated checks).
